port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: silent
external-controller: 127.0.0.1:9090

geox-url: 
  mmdb: "https://raw.githubusercontent.com/Masaiki/GeoIP2-CN/release/Country.mmdb"

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - +.msftconnecttest.com
    - +.msftncsi.com
    - +.xboxlive.com
    - msftconnecttest.com
    - xbox.*.microsoft.com
    - "*.battlenet.com.cn"
    - "*.battlenet.com"
    - "*.blzstatic.cn"
    - "*.battle.net"
  nameserver:
    - https://1.12.12.12/dns-query
    - https://223.5.5.5/dns-query
  fallback:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.alidns.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4

profile:
  tracing: true

proxy-providers:
  A:
    type: http
    path: ./profiles/proxies/A.yaml
    url: è®¢é˜…é“¾æ¥
    interval: 86400
    health-check:
      enable: true
      url: http://www.google.com/generate_204
      interval: 300      
      
proxy-groups:
  - name: ğŸ¬ï¸ æ²¹ç®¡å½±éŸ³
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡³ å…¶ä»–èŠ‚ç‚¹

  - name: âœˆï¸ ç”µæŠ¥æ¶ˆæ¯
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡³ å…¶ä»–èŠ‚ç‚¹
          
  - name: ğŸ‘¥ ç¤¾äº¤è½¯ä»¶
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡³ å…¶ä»–èŠ‚ç‚¹

  - name: ğŸ¤– äººå·¥æ™ºèƒ½
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡³ å…¶ä»–èŠ‚ç‚¹
      
  - name: ğŸŒŒ è°·æ­ŒæœåŠ¡
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹ 
      - ğŸ‡ºğŸ‡³ å…¶ä»–èŠ‚ç‚¹


  - name: ğŸªŸ å¾®è½¯æœåŠ¡
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡³ å…¶ä»–èŠ‚ç‚¹
      
  - name: ğŸŒï¸ ä»£ç†ç½‘ç«™
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡³ å…¶ä»–èŠ‚ç‚¹

  - name: â™¾ï¸ é»‘ç™½åå•
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡³ å…¶ä»–èŠ‚ç‚¹
      
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    type: url-test
    filter: '^(?=.*((?i)ğŸ‡­ğŸ‡°|é¦™æ¸¯|(\b(HK|Hong)\d{0,2}\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 150
    lazy: true
    use:
      - A

  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    type: url-test
    filter: '^(?=.*((?i)ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|(\b(JP|Japan)\d{0,2}\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 150
    lazy: true
    use:
      - A

  - name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
    type: url-test
    filter: '^(?=.*((?i)ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®|(\b(SG|Singapore)\d{0,2}\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 150
    lazy: true
    use:
      - A

  - name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
    type: url-test
    filter: '^(?=.*((?i)ğŸ‡ºğŸ‡¸|ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|(\b(US|United States)\d{0,2}\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 150
    lazy: true
    use:
      - A

  - name: ğŸ‡ºğŸ‡³ å…¶ä»–èŠ‚ç‚¹
    type: select
    filter: '^(?!.*((?i)ğŸ‡­ğŸ‡°|é¦™æ¸¯|(\b(HK|Hong)\d{0,2}\b)|ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|(\b(JP|Japan)\d{0,2}\b)|ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®|(\b(SG|Singapore)\d{0,2}\b)|ğŸ‡ºğŸ‡¸|ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|(\b(US|United States)\d{0,2}\b)))'
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 150    
    lazy: true
    use:
      - A

rule-providers:  
  Reject:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/Reject.yaml
    path: ./ruleset/Reject.yaml 
  Wechat:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/Wechat.yaml
    path: ./ruleset/Wechat.yaml 
  YouTube:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/YouTube.yaml
    path: ./ruleset/YouTube.yaml
  Telegram:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/Telegram.yaml
    path: ./ruleset/Telegram.yaml 
  Social:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/Social.yaml
    path: ./ruleset/Social.yaml 
  OpenAI:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/OpenAI.yaml
    path: ./ruleset/OpenAI.yaml 
  Google:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/Google.yaml
    path: ./ruleset/Google.yaml 
  Microsoft:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/Microsoft.yaml
    path: ./ruleset/Microsoft.yaml 
  Proxy:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy_Classical_No_Resolve.yaml
    path: ./ruleset/Proxy.yaml 
  Direct:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Classical_No_Resolve.yaml
    path: ./ruleset/Direct.yaml 
  LAN:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/LAN.yaml
    path: ./ruleset/LAN.yaml 

rules:
- RULE-SET,Reject,REJECT
- RULE-SET,Wechat,DIRECT
- RULE-SET,YouTube,ğŸ¬ï¸ æ²¹ç®¡å½±éŸ³
- RULE-SET,Telegram,âœˆï¸ ç”µæŠ¥æ¶ˆæ¯
- RULE-SET,Social,ğŸ‘¥ ç¤¾äº¤è½¯ä»¶
- RULE-SET,OpenAI,ğŸ¤– äººå·¥æ™ºèƒ½
- RULE-SET,Google,ğŸŒŒ è°·æ­ŒæœåŠ¡
- RULE-SET,Microsoft,ğŸªŸ å¾®è½¯æœåŠ¡
- RULE-SET,Proxy,ğŸŒï¸ ä»£ç†ç½‘ç«™
- RULE-SET,Direct,DIRECT
- RULE-SET,LAN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,â™¾ï¸ é»‘ç™½åå•


script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
