port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: silent
external-controller: 127.0.0.1:9090

dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
  default-nameserver:
     - 223.5.5.5
     - 223.6.6.6
     - 119.29.29.29
  nameserver:
     - https://223.5.5.5/dns-query
     - https://223.6.6.6/dns-query
     - https://1.12.12.12/dns-query
     
  fallback:
     - https://120.53.53.53/dns-query

profile:
  tracing: true

proxy-providers:
  A:
    type: http
    path: ./profiles/proxies/A.yaml
    url: è®¢é˜…é“¾æ¥
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300      
      
proxy-groups:
  - name: ğŸ¬ï¸ å½±éŸ³åª’ä½“
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡³ å…¶ä»–èŠ‚ç‚¹
          
  - name: ğŸ‘¥ ç¤¾äº¤åª’ä½“
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡³ å…¶ä»–èŠ‚ç‚¹

  - name: ğŸ è‹¹æœæœåŠ¡
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹   
      - ğŸ‡ºğŸ‡³ å…¶ä»–èŠ‚ç‚¹
      
  - name: ğŸŒŒ è°·æ­ŒæœåŠ¡
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹ 
      - ğŸ‡ºğŸ‡³ å…¶ä»–èŠ‚ç‚¹
      
  - name: ğŸŒï¸ ä»£ç†åŸŸå
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡³ å…¶ä»–èŠ‚ç‚¹
      
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    type: url-test
    filter: '^(?=.*((?i)ğŸ‡­ğŸ‡°|é¦™æ¸¯|(\b(HK|Hong)\d{0,2}\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 150
    lazy: true
    use:
      - A

  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    type: url-test
    filter: '^(?=.*((?i)ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|(\b(JP|Japan)\d{0,2}\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 150
    lazy: true
    use:
      - A

  - name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
    type: url-test
    filter: '^(?=.*((?i)ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®|(\b(SG|Singapore)\d{0,2}\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 150
    lazy: true
    use:
      - A

  - name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
    type: url-test
    filter: '^(?=.*((?i)ğŸ‡ºğŸ‡¸|ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|(\b(US|United States)\d{0,2}\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 150
    lazy: true
    use:
      - A

  - name: ğŸ‡ºğŸ‡³ å…¶ä»–èŠ‚ç‚¹
    type: select
    filter: '^(?!.*((?i)ğŸ‡­ğŸ‡°|é¦™æ¸¯|(\b(HK|Hong)\d{0,2}\b)|ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|(\b(JP|Japan)\d{0,2}\b)|ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®|(\b(SG|Singapore)\d{0,2}\b)|ğŸ‡ºğŸ‡¸|ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|(\b(US|United States)\d{0,2}\b)))'
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 150    
    lazy: true
    use:
      - A

rule-providers:
  LAN:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/LAN.yaml
    path: ./ruleset/LAN.yaml    
  Reject:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/Reject.yaml
    path: ./ruleset/Reject.yaml 
  Social:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/Social.yaml
    path: ./ruleset/Social.yaml 
  Media:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/Media.yaml
    path: ./ruleset/Media.yaml
  AI:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/AI.yaml
    path: ./ruleset/AI.yaml 
  AppleCDN:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/AppleCDN.yaml
    path: ./ruleset/AppleCDN.yaml
  AppleService:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/AppleService.yaml
    path: ./ruleset/AppleService.yaml
  Google:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/Google.yaml
    path: ./ruleset/Google.yaml 
  Proxy:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/Proxy.yaml
    path: ./ruleset/Proxy.yaml 
  Direct:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/Direct.yaml
    path: ./ruleset/Direct.yaml 

rules:
- RULE-SET,LAN,DIRECT
- RULE-SET,Reject,REJECT
- RULE-SET,Social,ğŸ‘¥ ç¤¾äº¤åª’ä½“
- RULE-SET,Media,ğŸ¬ï¸ å½±éŸ³åª’ä½“
- RULE-SET,AI,ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
- RULE-SET,AppleCDN,DIRECT
- RULE-SET,AppleService,ğŸ è‹¹æœæœåŠ¡
- RULE-SET,Google,ğŸŒŒ è°·æ­ŒæœåŠ¡
- RULE-SET,Proxy,ğŸŒï¸ ä»£ç†åŸŸå
- RULE-SET,Direct,DIRECT
- MATCH,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
